### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by rieschl**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

This PR adds a GitHub Action workflow according to https://gist.github.com/weierophinney/b003e50c3c2667d08076caf31ebd36a4

* remove `travis.yml`
* commit `composer.lock` to repo
* remove `CHANGELOG` file
* adapt `.gitattributes` and `.gitignore` files

### CODE REVIEW

**Comment by froschdesign** [comment]
@rieschl 
Please update also the readme file and replace the current badges with:

```markdown
[![Build Status](https://github.com/laminas/laminas-mvc-middleware/workflows/continuous-integration.yml/badge.svg)](https://github.com/laminas/laminas-mvc-middleware/actions/workflows/continuous-integration.yml)
```

**Comment by rieschl** [comment]
> @rieschl
> Please update also the readme file and replace the current badges with:

@froschdesign Should I remove both badges? Travis ans Coveralls?

**Comment by boesing** [comment]
Coveralls is still used and thus, coverage should work.
I've seen other PRs where we kept it but removed the master branch. Not sure if that works but there was a coverage badge available tho.

**Review by boesing — APPROVED** [review]
LGTM

**Comment by rieschl** [comment]
> Coveralls is still used and thus, coverage should work.
> I've seen other PRs where we kept it but removed the master branch. Not sure if that works but there was a coverage badge available tho.

Hm, @weierophinney said on [Slack](https://laminas.slack.com/archives/C4R13GTRD/p1617727979140200?thread_ts=1617711764.128300&cid=C4R13GTRD):
>> is it correct that coverage status is removed?
>
> Yes, for now. We're trying to decide if we want to continue with coveralls (which we largely ignored, unless we saw a huge  decrease), or move to something like mutation testing instead. (Or if we want to use a different service for coverage entirely.)

That said/quoted, I'm happy to re-add the badge if you want to 🙂

**Pull request merged**
