### PR TITLE
PHP 8 support

### LINKED ISSUE #5: PHP 8.0 support
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

### PR DESCRIPTION
**Pull request by rieschl**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

adds support for PHP 8

* [x]  Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
* [x]  Modify `composer.json` to drop support for PHP less than 7.3
* [x]  Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
* [x]  Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
* [x]  Modify `.travis.yml` to add PHP 8.0 to the matrix (_NOTE_: Do not allow failures as PHP 8.0 has a feature freeze since 
* [x]  Modify source code in case there are incompatibilities with PHP 8.0 (there were none)

fixes #5

### CODE REVIEW

**Comment by froschdesign** [comment]
@rieschl 
We have to switch to the [GitHub action continuous integration workflow](https://gist.github.com/weierophinney/b003e50c3c2667d08076caf31ebd36a4) before we can continue with PHP 8.0 and the Psalm integration. Otherwise, no checks will be run.

**Comment by rieschl** [comment]
> We have to switch to the [GitHub action continuous integration workflow](https://gist.github.com/weierophinney/b003e50c3c2667d08076caf31ebd36a4) before we can continue with PHP 8.0 and the Psalm integration. Otherwise, no checks will be run.

ugh, stupid travis. hold on, I'll try to come up with a PR for that.

**Comment by rieschl** [comment]
> We have to switch to the [GitHub action continuous integration workflow](https://gist.github.com/weierophinney/b003e50c3c2667d08076caf31ebd36a4) before we can continue with PHP 8.0 and the Psalm integration. Otherwise, no checks will be run.

Here you go: https://github.com/laminas/laminas-mvc-middleware/pull/12

**Comment by rieschl** [comment]
> We have to switch to the [GitHub action continuous integration workflow](https://gist.github.com/weierophinney/b003e50c3c2667d08076caf31ebd36a4) before we can continue with PHP 8.0 and the Psalm integration. Otherwise, no checks will be run.

@froschdesign I rebased that PR onto the current `2.0.x` branch (which has already #12/GHA merged).

**Pull request merged**
